import Config

# Configure your database
config :until_midnight, UntilMidnight.Repo,
  database: System.get_env("POSTGRES_DATABASE", "untilmidnight"),
  username: System.get_env("POSTGRES_USER", "docker"),
  password: System.get_env("POSTGRES_PASSWORD", "docker"),
  hostname: System.get_env("POSTGRES_HOST", "localhost"),
  port: String.to_integer(System.get_env("POSTGRES_PORT", "5432")),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("POSTGRES_POOLSIZE", "10"))

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :until_midnight, UntilMidnightWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 8000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ntUlu7aU8mq9J4n71P44+49hJvX8ED1VHCT5kH/54iVhTjAZbS7tkGK4Eyw8EIJD",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},

    # Start the tailwind css watcher
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :until_midnight, UntilMidnightWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/[^uploads].*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/until_midnight_web/(live|views)/.*(ex)$",
      ~r"lib/until_midnight_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
